spring:
  application:
    name: demo_sc
  jpa:
    #show-sql: true
    properties:
      hibernate:
        # sql ????? ???? ?? ??
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      # ???? ?? ??, ?? => ??? ??
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/sess_db
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console